Module resolution points to invalid file
Module resolution points to invalid file in node package.json

module.js:471
    throw err;
    ^

Error: Cannot find module 'coinpayments'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

Please test your package after rolling it to npm thanks! :)